### ISSUE TITLE
echo_dualstack fails on my MacBook

### ISSUE THREAD

**Issue by djc** [djc/quinn#245]
Tests on master are failing for me:

```
---- tests::echo_dualstack stdout ----
INFO connecting from [::]:0 to 127.0.0.1:60805
thread 'tests::echo_dualstack' panicked at 'assertion failed: `(left == right)`
  left: `13`,
 right: `16`', quinn/src/platform/cmsg.rs:69:5
```

This is with macOS 10.14.2.

**Comment by Ralith** [comment]
Ugh, what a weird inconsistency with CI. Do the other two integration tests pass? If you break on the failure, what're `cmsg.cmsg_level` and `cmsg.cmsg_type` at unix.rs:157?

**Comment by djc** [comment]
```
running 3 tests
test tests::echo_dualstack ... FAILED
test tests::echo_v4 ... ok
test tests::echo_v6 ... ok

failures:

---- tests::echo_dualstack stdout ----
INFO connecting from [::]:0 to 127.0.0.1:49702
[quinn/src/platform/unix.rs:157] cmsg.cmsg_level = 0
[quinn/src/platform/unix.rs:157] cmsg.cmsg_type = 27
[quinn/src/platform/unix.rs:157] cmsg.cmsg_level = 41
[quinn/src/platform/unix.rs:157] cmsg.cmsg_type = 36
thread 'tests::echo_dualstack' panicked at 'assertion failed: `(left == right)`
  left: `13`,
 right: `16`', quinn/src/platform/cmsg.rs:69:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Ralith** [comment]
That's `(IPPROTO_IP, IP_RECVTOS)` received by the IPv4 server, followed by `(IPPROTO_IPV6, IPV6_TCLASS)` received by the IPv6 client. `IPV6_TCLASS` [is clearly documented](https://github.com/apple/darwin-xnu/blob/master/bsd/netinet6/in6.h#L594) as yielding `int`, but apparently that's a lie on dual-stack sockets, though if `echo_v6` passes it must still hold for the single-stack case. Since Travis is passing consistently on 10.13, maybe this was a bug Apple introduced in 10.14?

Tonight I'll try adding a special case branch on `cmsg_len` to work around it.

**Comment by Ralith** [comment]
My understanding is that we've reported this to Apple as kernel ABI breakage; have they confirmed the issue?

**Comment by djc** [comment]
No, I've heard nothing from them. Will ping ekinnear on Slack.
