### ISSUE TITLE
MAX_STREAM_DATA on unopened stream

### ISSUE THREAD

**Issue by nbaksalyar** [djc/quinn#262]
Hello,

We're testing the same example described in #257, but the case is slightly different: instead of running 50 clients on one machine, we now run 1 client on each of 50 different machines. Generally, it works fine with a smaller number of connections (i.e. if we run 15 clients), but if we add more clients, occasionally they can fail with the following error:

```
ReadError(ConnectionClosed(ConnectionClosed { reason: ConnectionClose { error_code: STREAM_STATE_ERROR, frame_type: None, reason: b"MAX_STREAM_DATA on unopened stream" } })) - Read Error: connection closed: aborted by peer: received a frame for a stream that was not in a state that permitted that frame: MAX_STREAM_DATA on unopened stream
```
For now, we don't know where exactly it comes from, but maybe you have any pointers or ideas about what it could be?

We'll be continuing to research this case and we'll try to provide a minimal repro example as well. For now, we use the same client code that can be found here: https://github.com/ustulation/using-quinn/blob/master/examples/client_node.rs (or almost the same thing without our wrapper lib: https://github.com/povilasb/quinn-tests/blob/master/src/main.rs).

Thanks!

**Comment by Ralith** [comment]
The error suggests we're not properly ignoring flow control updates for send streams that have been closed and forgotten about. Normally this wouldn't be observable because gracefully finishing a stream involves waiting for all sent data to be acknowledged before forgetting about the stream, which means the receiver knows we've closed and won't send any further flow control updates. However, packet reordering (more likely on a physical network!) would cause the error to manifest.

This should be an easy fix; I'll see if I can repro in a unit test and resolve the root cause tonight.
