### ISSUE TITLE
Occasional 'specified instant was later than self' panic

### ISSUE THREAD

**Issue by nbaksalyar** [djc/quinn#290]
When running a quinn test with 50 nodes on a single machine, sometimes executables panic with this error:
```
thread 'Crust-Event-Loop' panicked at 'specified instant was later than self', src/libstd/sys/unix/time.rs:292:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:412
   6: std::sys::unix::time::inner::Instant::sub_instant::{{closure}}
             at src/libstd/sys/unix/time.rs:292
   7: <std::time::Instant as core::ops::arith::Sub>::sub
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:764
             at src/libstd/sys/unix/time.rs:291
             at src/libstd/time.rs:218
             at src/libstd/time.rs:307
   8: quinn_proto::connection::Connection::on_ack_received
   9: quinn_proto::connection::Connection::process_early_payload
  10: quinn_proto::connection::Connection::handle_decode
  11: quinn_proto::connection::Connection::handle_event
  12: <quinn::connection::ConnectionDriver as futures::future::Future>::poll
  13: <quinn::endpoint::EndpointDriver as futures::future::Future>::poll
  14: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
  15: futures::task_impl::std::set
  16: tokio_current_thread::CurrentRunner::set_spawn
  17: <tokio_current_thread::scheduler::Scheduler<U>>::tick
  18: <tokio_current_thread::Entered<'a, P>>::block_on
  19: <std::thread::local::LocalKey<T>>::with
  20: <std::thread::local::LocalKey<T>>::with
  21: <std::thread::local::LocalKey<T>>::with
  22: <std::thread::local::LocalKey<T>>::with
  23: tokio::runtime::current_thread::runtime::Runtime::block_on
```
which also results in this panic on `PoisonError`, [originating in `EndpointDriver`](https://github.com/djc/quinn/blob/f6c1ef0786af521e6238bff62a190657889a3993/quinn/src/endpoint.rs#L155):
```
thread 'Crust-Event-Loop' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x5626251dfab3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf8722b0178fb1b63
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x5626251db168 - std::sys_common::backtrace::_print::hc40139e5f1d656ee
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x5626251de3d2 - std::panicking::default_hook::{{closure}}::h993d43465919c16a
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x5626251de144 - std::panicking::default_hook::h73d2c2ec3d9ba5a4
                               at src/libstd/panicking.rs:215
   4:     0x5626251deae0 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                               at src/libstd/panicking.rs:478
   5:     0x5626251de661 - std::panicking::continue_panic_fmt::h3557b3c3fa21b47b
                               at src/libstd/panicking.rs:385
   6:     0x5626251de545 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x5626251f5dac - core::panicking::panic_fmt::h74ee8034b317ceed
                               at src/libcore/panicking.rs:85
   8:     0x5626250b848f - core::result::unwrap_failed::h8e0ac499f0964c9c
   9:     0x5626250ab4ad - <quinn::endpoint::EndpointDriver as core::ops::drop::Drop>::drop::h057251ce9fb61ad9
  10:     0x562624fedf5c - core::ptr::real_drop_in_place::h11999c79ac122fc4
  11:     0x562624fe2711 - tokio_current_thread::scheduler::release_node::hdfa6993967bc3b87
  12:     0x562624fe6d1b - <std::thread::local::LocalKey<T>>::with::h88be19ae1bcac8d9
  13:     0x562624fe2ccc - core::ptr::real_drop_in_place::h6f7e20259c368ab9
  14:     0x562624fe4e0c - <tokio_current_thread::scheduler::Scheduler<U>>::tick::h692590a11ed1c6b4
  15:     0x562624fefb76 - <tokio_current_thread::Entered<'a, P>>::block_on::h81e5daa8599ead48
  16:     0x562624fe71b2 - <std::thread::local::LocalKey<T>>::with::h96ce2096b2eb3e86
  17:     0x562624fe84df - <std::thread::local::LocalKey<T>>::with::hd85b763757785b58
  18:     0x562624fe5d18 - <std::thread::local::LocalKey<T>>::with::h0a1df7c8f13fbece
  19:     0x562624fe6f10 - <std::thread::local::LocalKey<T>>::with::h8def8c600f94357e
  20:     0x562624fd85fa - tokio::runtime::current_thread::runtime::Runtime::block_on::h63986fba4cba36b5
  21:     0x562624fccd19 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9dd8e7f43470e516
  22:     0x5626251e23f9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:92
  23:     0x562624ff906b - <F as alloc::boxed::FnBox<A>>::call_box::hc7a6b11467f7d8dd
  24:     0x5626251e17bd - std::sys::unix::thread::Thread::new::thread_start::h6fb76bcf544b6181
                               at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:81
  25:     0x7f0e37a646da - start_thread
  26:     0x7f0e3757588e - __clone
  27:                0x0 - <unknown>
```

Any ideas why this might happen? We'll try to come up with a minimal repro example if it's something that's hard to track.

**Comment by Ralith** [comment]
Thanks for the report! If I'm eyeballing things correctly, that backtrace indicates that we're receiving an ACK for a packet with a timestamp earlier than the packet was sent. On the face of it this seems like it must indicate that we're scrambling our stored timestamps somehow, but we've seen this before and I have a pretty good hypothesis what's going on here: if you're using tokio's multithreaded runtime, `on_ack_received` is passed an `Instant` sampled on the `EndpointDriver`'s thread, which may not be perfectly in sync with the one computed on the `ConnectionDriver`'s thread for `poll_transmit`. On a local machine round-trip times may be small enough (i.e. effectively instantaneous) that the timestamp desync eclipses them, producing these seemingly impossible panics.

I believe this can be fixed by using an `Instant` sampled on the `ConnectionDriver`'s thread for the time of incoming datagrams. Doing this consistently for the initial packet might require some effort, but the case that's actually failing here, packets on an already-constructed connection, is an easy change.

**Comment by ustulation** [comment]
> if you're using tokio's multithreaded runtime

Though i think @nbaksalyar might be using the part of code involving eventloop as is in which case everything is `runtime::`current_thread`. Correct me if wrong though @nbaksalyar .

Anyway if there's a bug in multithreaded scenario and it's been identified then that's a good thing too!

**Comment by nbaksalyar** [comment]
Correct, the example uses the `tokio_current_thread` executor.

>On a local machine round-trip times may be small enough

And to update on this: I've just tried it with 50 machines in a local network on Digital Ocean and I'm seeing the same error.

**Comment by Ralith** [comment]
Hmm, must be something else then. I'll review the timestamp wrangling code, and a repro would certainly be helpful.

**Comment by Ralith** [comment]
What CPUs and kernel versions have you observed this on?

**Comment by Ralith** [comment]
I see what's going on here. The interesting thing about the above backtraces is that `ConnectionDriver::poll` is being called from `EndpointDriver::poll`, which indicates that the connection hasn't been yielded to the application yet; we're still in `EndpointInner::drive_incoming`. This is called from `EndpointDriver::poll`'s main loop, which is also responsible for dispatching incoming datagrams to connections. The `Instant` it tags those datagrams with is sampled once, on entry to `EndpointDriver::poll`, but `ConnectionDriver::poll` samples its own `Instant` when invoked, which will necessarily be greater than the `EndpointDriver`'s by monotonicity. This leads to the following sequence of events

1. `EndpointDriver::poll` samples an `Instant`; let's call that t0.
2. `EndpointDriver::poll` invokes `ConnectionDriver::poll`, which samples the later `Instant` t1 and invokes `quinn_proto::Connection::poll_transmit` with it, recording t1 as the send time.
3. The generated packet is transmitted, but due to a large number of connections being received by a single endpoint, `EndpointInner::drive_recv` and/or `EndpointInner::drive_send` bail out before all data is transmitted to avoid starving eachother/other endpoint related processing, setting `keep_going = true`.
4. After one or more such `EndpointInner::poll` loop repetitions, an ACK of the generated packet is received, and forwarded to the connection. Because `EndpointInner::poll` never actually returned, the new packet is still tagged with t0, which is less than t1, hence the panic.

This can be fixed the same way as the original hypothesis: by using the `ConnectionDriver`'s timestamp for incoming packets instead of the `EndpointDriver`'s. It would also be sufficient, and might be prudent regardless, to update the timer on each iteration of the `poll` loop.

**Comment by Ralith** [comment]
Should be by #295 regardless of #291's state.
