### ISSUE TITLE
Discuss how TLS `ClientConfig` should be passed around

### ISSUE THREAD

**Issue by djc** [djc/quinn#35]
@Ralith made the argument that this should be an argument to `connect()` instead of a global configuration setting in `Config`.

I'm actually not quite convinced. We currently change the following things:

* Toggle key log
* Trust anchors
* TLS protocol version
* ALPN protocol

I would argue that it makes sense to set these things on a per-`Endpoint` basis.

**Comment by Ralith** [comment]
A client may want to communicate with different types of servers via different protocols without allocating redundant endpoints, so per-connection ALPN is necessary as a baseline. On review I don't actually see anything else in `ClientConfig` that seems obviously useful (and rustls is mistakenly using `String` for ALPN IDs there too) so maybe it would be better to define our own API just for that.

**Comment by djc** [comment]
And abstract over cloning the underlying `ClientConfig` and mutating the clone? Maybe we should open an issue in rustls to see what they think about changing the API around this? (Something like `ClientSession::with_alpn_protocols(..)` that overrides the `Config`s defaults.)

**Comment by Ralith** [comment]
Another per-connection variable could be certificate verification overrides, which we'll want sooner or later (not just for untrusted connections, but also for unconventional verification schemes like Perspectives).

> Maybe we should open an issue in rustls to see what they think about changing the API around this?

Is there that much room for improvement over duplicate config objects? They're not *that* big, are they?

**Comment by djc** [comment]
> Is there that much room for improvement over duplicate config objects? They're not that big, are they?

The documentation says:

> Making one of these can be expensive, and should be once per process rather than once per connection.

It's not quite clear whether that means cloning would also be affected.

I really don't think we should be optimizing for per-connection certificate verification overrides until a concrete use case comes up.

**Comment by djc** [comment]
I clarified the method name; I think adding CAs (rather than setting one) would mostly cover that?

**Comment by Ralith** [comment]
For P2P, TOFU, or sidechannel-based verification systems, a CA wouldn't accomplish anything. Sometimes you just want to talk to someone that hasn't been vouched for in advance by a central authority.

**Comment by djc** [comment]
CA in this context doesn't mean something in Mozilla's root store, but just the certificate chain root.

**Comment by Ralith** [comment]
I got that; the problem is that there is no trust authority in those systems, so the only way to have a CA would to to distribute its keys with the software, which would make it meaningless--just an elaborate and confusing workaround for an API limitation. Even if you were okay with that sort of hacky work around, you absolutely wouldn't want such a CA to globally apply to outgoing connections from the same application to services that *can* be verified by traditional CAs.

**Comment by djc** [comment]
Other trickiness in the `EndpointBuilder` API that might be relevant: it currently allows a reset of the `Config` with the `config()` method (from the `Config::default()` it initializes with), but some of the methods also change the `Config`, so if called in some orders, some stuff gets thrown away.

Also sticky: what if Quinn is used in a HTTP context in a stack that can do either QUIC, H2 or 1.1, we may want to share the TLS configs for both (at least some parts).

**Comment by icefoxen** [comment]
I definitely would like the ability to connect to untrusted hosts, since I'm using this crate for a P2P network experiment.  Not much point in having a CA and chain of trust in such a situation.

Right now I can do that just by having the CA certificate built into the program, but as Ralith says it's essentially useless if not worse than useless.  It also makes unit testing a little less convenient than it could be, though that's not as big an idea.

For the `EndpointBuilder` thing, I dunno if it's applicable but I handle this in `ggez` just by documenting the behavior and making it transparent what structs the builder is made out of.  The jury is still out on whether that is at all troublesome though.

**Comment by djc** [comment]
I think this has mostly settled down now, and can be closed?

**Comment by Ralith** [comment]
Good call.
