### ISSUE TITLE
Question regarding checksum & decryption error

### ISSUE THREAD

**Issue by jean-airoldie** [djc/quinn#453]
Does quinn implement an additional checksum on top of UDP's 16bit crc? I glanced over the QUIC specs and I couldn't find anything on the subject.

Moreover, are decryption errors always fatal?

**Comment by Ralith** [comment]
All QUIC implementations verify the integrity of packets using AEAD; see [Protected Packets](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#packet-protected) for details. All currently supported AEAD tags are 128-bit, though future TLS extensions may add other options.

Failure to decrypt and authenticate a packet results in the packet being discarded. We can't kill the connection in this case because that would make it trivial for off-path attackers to kill connections by injecting a spoofed packet, similar to how certain ISPs have historically interfered with activity by spoofing TCP RSTs.

**Comment by jean-airoldie** [comment]
Nice, exactly what I was looking for.
