### ISSUE TITLE
`SendStream::poll_flush` lies

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#519]
The contract of `AsyncWrite::poll_flush` is that the returned future will not resolve until either all data has been successfully flushed or an error has occurred.  However, `SendStream::poll_flush` [is a no-op].  This presents a problem for libp2p, which needs to know when all the peer has received all data on a connection.

[is a no-op]: </djc/quinn/blob/ac810125c1ff764f4d4828fd19cbee7a3079dea6/quinn/src/streams.rs#L135-L137>

**Comment by Ralith** [comment]
`poll_flush` guarantees that data is not stuck in a buffer waiting for more data to be written, which isn't something quinn currently does ever. If you want to ensure that all data has been *delivered*, use `SendStream::finish`.

**Comment by DemiMarie-parity** [comment]
@Ralith I interpret the docs differently:

> Attempt to flush the object, ensuring that any buffered data reach their destination.
> 
> On success, returns `Poll::Ready(Ok(()))`.
> 
> If flushing cannot immediately complete, this method returns `Poll::Pending` and arranges for the current task (via `cx.waker().wake_by_ref()`) to receive a notification when the object can make progress towards flushing.
> 
> # Implementation
> 
> This function may not return errors of kind `WouldBlock` or `Interrupted`.  Implementations must convert `WouldBlock` into `Poll::Pending` and either internally retry or convert `Interrupted` into another error kind.

To me, this implies that `poll_flush` must not resolve until all previously-sent data has been delivered.  `SendStream::finish` does ensure that, but it also renders the stream unusable, which is a blocker for libp2p.  That said, the docs are currently ambiguous.

**Comment by Ralith** [comment]
I agree that the documentation is unclear, but I stand by my interpretation. For example, refer to the behavior of [`std::net::TcpStream::flush`](https://doc.rust-lang.org/src/std/net/tcp.rs.html#589).

It is possible to implement a future to wait for delivery of data up to a certain point in a stream, but before expanding our API I'd like to better understand what problem you're trying to solve. What does libp2p do on other transports? What are you using this information for? What happens when delivery is confirmed but the remote application terminates before actually reading your data from the transport?

**Comment by DemiMarie-parity** [comment]
@Ralith On other transports, libp2p seems to do what quinn already does.  Closing.
