### ISSUE TITLE
Allow connection to return peer certificates

### ISSUE THREAD

**Issue by zeroqn** [djc/quinn#567]
Experiment on implement [libp2p-tls](https://github.com/libp2p/specs/blob/master/tls/tls.md).

But it need peer's certificates. I see rustls has ```get_peer_certificates``` func on ```Session``` trait. 
Consider add it to ```crypto::Session``` in quinn-proto and ```Connection``` in quinn.

**Comment by djc** [comment]
I'm not sure it makes sense to do this at the Quinn layer. Couldn't you implement this as a rustls `ClientCertVerifier`?

**Comment by Ralith** [comment]
This could definitely be done in `ClientCertVerifier`, but you'd have to extract the data through a side channel which is a bit of a pain. An accessor at the `Connection` level would be much more convenient, and rustls's method on `Session` is precedent, so I lean in favor.

**Comment by djc** [comment]
It seems to me the fix for that would be to fix the `ClientCertVerifier` API to make this kind of thing easier on that side, rather than exposing specific APIs for the `crypto::Session` API.

I'd really prefer to avoid putting TLS-specific APIs in `Connection` or the crypto APIs, to keep it flexible for very different implementations of crypto protocols.

**Comment by djc** [comment]
Just linking this here for reference: https://github.com/zeroqn/quinn/commit/5f216f1db423b548c760ed39f4994e42804adb54

**Comment by Ralith** [comment]
> It seems to me the fix for that would be to fix the ClientCertVerifier API to make this kind of thing easier on that side.

What would that look like?

> I'd really prefer to avoid putting TLS-specific APIs in Connection or the crypto APIs, to keep it flexible for very different implementations of crypto protocols.

I agree that this is important, and I don't think it's necessarily an obstacle here. I think practically any reasonable cryptographic protocol will have *some* form of strongly identifying information about the peer, which could be defined as an associated type and exposed through a method that doesn't have "certificate" specifically in the name.

**Comment by zeroqn** [comment]
Even if i save client's certificates, i need one more RTT to associate client's identity to connection.
Is it possible to do this without one more RTT?

> I think practically any reasonable cryptographic protocol will have some form of strongly 
> identifying information about the peer, which could be defined as an associated type and 
> exposed through a method that doesn't have "certificate" specifically in the name.

I agree.

**Comment by Ralith** [comment]
> Is it possible to do this without one more RTT?

You need to wait until the handshake's complete regardless from a cryptographic correctness standpoint, I think.

**Comment by zeroqn** [comment]
Maybe we can cut into two parts?
- ```quinn```'s Connection
- ```quinn-proto```'s Connection 

Since ```quinn-proto```'s Connection still has access to Session object, maybe
we can add these.

```rust
    // Session trait
    fn identity<R: Send, F: Fn(&Self) -> R>(&self, f: F) -> R;
```
```rust
   // quinn-proto's Connection
    pub fn identity<R: Send, F: Fn(&S) -> R>(&self, f: F) -> R {
        self.tls.identity(f)
    }
```

**Comment by djc** [comment]
So, the spec you linked to describes a certain custom authentication during the TLS handshake. If that's what you intend to implement, I can't see why you need `identity()` methods on `Connection` types, which pretty much will not allow you to influence the TLS handshake. At best, they will allow you to verify after the fact and then terminate the handshake. And, given the linked spec, these probably won't give you access to the custom extension data you need. As such, what you're asking for (Quinn types API for identity) doesn't seem to match the stated use case (implementing a particular way of performing TLS handshakes).

**Comment by Ralith** [comment]
Yeah, fiddling with the handshake will require working with rustls, not quinn.

**Comment by DemiMarie-parity** [comment]
@djc In my own implementation of libp2p-quic, (https://github.com/DemiMarie-parity/rust-libp2p/tree/demi-quic-stable-futures), I will be requiring that there be exactly one peer certificate, but otherwise accepting any certificate.  I will then obtain the certificate after the handshake has completed, and then verify it.  If the certificate turns out to be bad, the connection will be dropped.

**Comment by djc** [comment]
It sounds to me like the conceptually correct way to do this would still be to solve this during the handshake at the rustls level, but the simple getter seems okay to expose in the `Connection`.

**Comment by zeroqn** [comment]
Since #594 is merged, close this issue.
Thanks.

**Comment by kim** [comment]
Sorry reopen this topic, but I seem to be stuck with the same problem: _after_ the connection is authenticated, I’d like to retrieve who was authenticated. Yes this is in a p2p context, too, but seems generally useful, especially when client certificate authentication is used.

@djc Would you consider a PR along the lines of what @Ralith and @zeroqn proposed  (ie. ably exposing the authentication data, not the session)?

**Comment by djc** [comment]
I still think that makes more sense as part of rustls than as part of Quinn. Maybe open an issue in rustls? Feel free to cc me.

**Comment by kim** [comment]
@djc Well, I can make rustls perform custom certificate validation, that's not the problem. Since rustls is not aware of a `quinn-proto` `Connection`, and the `quinn` `Connection` hides the `quinn-proto` one, there is just no way to access the authentication data. 

Just to double check there's no misunderstanding in why this is useful: it is not so uncommon anymore to use client certificates for both authentication _and_ authorization on the application level. For example, [kubernetes](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs) does this. With the current `quinn` API, this is not possible, because there is no way to access the client certificate (or attributes thereof) after successfull authentication.

**Comment by djc** [comment]
We discussed this a bit in https://github.com/djc/quinn/pull/596#discussion_r365992086. I don't doubt the usefulness, we just have to work out the right abstractions and API for this.

**Comment by kim** [comment]
Got it, thanks. Let me see if I can come up with a proposal.

**Comment by DemiMarie-parity** [comment]
@kim That is actually not true (and libp2p-quic does it).  The trick is to get them from the underlying `crypto::Session` object, which in this case is `rustls`.

**Comment by djc** [comment]
@DemiMarie-parity it's not clear to me what it is you think is not true. Do remember that @kim appears to be working at the quinn layer, where the `crypto::Session` isn't currently available like it is at the quinn-proto layer.

**Comment by DemiMarie-parity** [comment]
I forgot about that, sorry @djc!  I am so used to working with `quinn-proto` that I forgot about `quinn`.
