### ISSUE TITLE
Support for zero-byte STREAM messages

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#625]
Would it be possible to support sending a zero-byte STREAM frame immediately after opening a stream, so that the peer is made aware of the stream having been opened?

**Comment by Ralith** [comment]
Can you elaborate on your use case for this?

**Comment by DemiMarie-parity** [comment]
In libp2p-quic, it would be nice to if opening a stream notified the peer immediately, rather than waiting until some data was sent.  Would this come at a significant performance hit?

**Comment by Ralith** [comment]
It would come at a nonzero complexity cost. What are you doing that requires that behavior?

**Comment by DemiMarie-parity** [comment]
It is mostly to make QUIC act like other mulitplexers, such as yamux.  If I open a stream and immediately read from it, this works fine with yamux, but deadlocks with QUIC.

I can (and probably should) complain loudly if that happens, but it is still a non-obvious footgun.  It would be nice if I could detect that and send a zero-byte STREAM frame.  That would make the peer aware of the stream so it could write to it, breaking the deadlock.

**Comment by djc** [comment]
This seems like a pretty niche requirement. Why don't you emulate it by sending (and consuming) a one-byte stream prefix?

**Comment by DemiMarie-parity** [comment]
First, libp2p is a standard with many implementations.  Other QUIC libraries may not have this limitation, so having to include a one-byte stream prefix hurts them pointlessly.

Secondly, doing so hurts performance if the side opening the stream is in fact the first one to send data on it.  This is always the case in practice in libp2p, but requiring it to be so is a footgun.

My current plan is to return an explicit error to the caller in this case.

**Comment by Ralith** [comment]
> It is mostly to make QUIC act like other mulitplexers, such as yamux

QUIC streams are not intended to exactly replicate the semantics of TCP connections. QUIC is not an off-the-shelf TCP multiplexer. If you want to build an application-layer protocol which itself tunnels TCP connections, @djc's suggestion sounds like a reasonable approach to me.

> I can (and probably should) complain loudly if that happens, but it is still a non-obvious footgun.

I don't think this is a problem for any reasonable application protocol, since it is natural for the peer who wishes to send data to be the one who opens a stream to do so. If that's the server, then the server is free to do so immediately upon accepting a connection. It sounds like you're trying to tunnel unaware applications through QUIC; you should not expect to be able to do so without introducing (potentially trivial) semantics of your own.

> Other QUIC libraries may not have this limitation, so having to include a one-byte stream prefix hurts them pointlessly.

To my knowledge, no QUIC implementation provides this behavior. The semantics of QUIC are that streams open lazily, and it would be strange to deliberately undermine that.

> Secondly, doing so hurts performance if the side opening the stream is in fact the first one to send data on it.

A one-byte header on a stream that is being used to carry a TCP session will certainly not have a measurable impact on performance. I encourage you to try it and measure if you're still concerned.

**Comment by DemiMarie-parity** [comment]
Thank you for the explanation!  Would it be possible to return a more helpful error in this case?  If not, I can prepare a PR for the documentation.

**Comment by Ralith** [comment]
> Would it be possible to return a more helpful error in this case?

While I sympathize with the desire, unfortunately I don't think we can do that. Consider an application protocol that proceeds something like:
```rust
let mut (meta_send, meta_recv) = conn.open_bi().await?;
tokio::spawn(async move { while let Some(msg) = read_msg(&mut meta_recv) { ... }});
conn.open_uni().await?.write_all(b"elicits a response on meta_recv").await?;
```
Sending data on the second stream implicitly opens the first, at which point the peer can write to it freely. Returning an error when reading from a stream that hasn't been formally opened would substantially complicate successfully employing this reasonable pattern.

> If not, I can prepare a PR for the documentation.

That would be great, thanks! We already call this out explicitly [in the high-level API](https://docs.rs/quinn/0.5.3/quinn/struct.Connection.html#method.open_uni), but doing something similar in quinn-proto as well is reasonable.
