### ISSUE TITLE
SendStream: poll_write with zero-length buffer panics

### ISSUE THREAD

**Issue by kwantam** [djc/quinn#853]
Attempting to write a zero-length buffer with `futures::io::AsyncWrite::poll_write` on a SendStream causes a panic (this is in the crates.io version, 0.6.1):

```
thread 'tests::broadcast_receiver_close' panicked at 'attempt to subtract with overflow',
    quinn-proto-0.6.1/src/range_set.rs:158:42
```

I don't have time this very moment to make a full test case, but the following should trigger it repeatably:

```rust
// send is a SendStream
Pin::new(&mut send).poll_write(cx, &[])
```

Please let me know if a more complete test case would be useful; happy to come up with one.

By the way: the reason I want to attempt a zero-length write is to try and detect that the receiver has dropped the other end. Maybe there's a more natural way to do this that I'm just missing... Thoughts?

Thank you!

**Comment by Ralith** [comment]
Thanks for the report! I believe this is a duplicate of https://github.com/djc/quinn/issues/846, which was fixed in 9cf8652deb89f16e236bc3d4fe46a42793a4c036. We should probably make a new release soon, since this is coming up repeatedly.

> By the way: the reason I want to attempt a zero-length write is to try and detect that the receiver has dropped the other end. Maybe there's a more natural way to do this that I'm just missing... Thoughts?

Just so; `SendStream::stopped` was introduced in https://github.com/djc/quinn/pull/755, which hasn't made it into a release yet.

**Comment by kwantam** [comment]
Ah, great! Sorry that I missed it---didn't find quite the right search terms. And `stopped()` sounds perfect---thank you!

**Comment by Ralith** [comment]
No worries, we certainly don't expect users to always be aware of the latest developments!
