### ISSUE TITLE
Encountering premature end of stream when using ordered read API

### ISSUE THREAD

**Issue by Matthias247** [djc/quinn#857]
When I tried to modify the benchmark example from using unordered reads to ordered reads I encountered an issue that the client/writer panic'd while sending more data:

> Error writing: ConnectionClosed(ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" }))

While digging a bit deeper into why it happened, it seems like the reader yielded `Ok(None)` before, which probably lead the stream to be cancelled. However this shouldn't have happened if the writer had more data.

The modified read loop is just:

```rust
let mut buffer = [0u8; 32*1024];
loop {
    match stream.read(&mut buffer[..]).await {
        Ok(None) => {
            println!("End of stream");
            return;
        }
        Ok(Some(n)) => {
            println!("Read {} bytes", n);
            continue;
        }
        Err(e) => {
            println!("Error during reading: {:?}", e);
            return;
        }
    }
}
```

Full code/repro: https://gist.github.com/Matthias247/3797269ca948ce4025224041870eb377
This can be copied in the bench folder and run with `cargo bench`.

I'm not seeing me doing anything particularly wrong here - so I guess there might be a bug where reads return `None` before the actual end of the stream?

**Comment by Ralith** [comment]
Thanks for the report! I was able to reproduce the reported behavior, and I agree with your initial diagnosis. Will investigate.

**Comment by Ralith** [comment]
It looks like this is actually working as intended. I was briefly confused as I didn't realize the benchmark function was being ran from scratch many times.

What you're observing is a subtle application-layer race condition:
1. Writer sends all data
2. Reader receives all data, sends acknowledgements and close (implied because your `return` at end of stream drops all handles)
3. Acknowledgements are possibly delayed or lost
4. Writer receives close and reports it to all outstanding futures.

If the acknowledgements are delayed, the repro panics on `stream.finish().await.unwrap()`. If they aren't, then `stream.finish()` succeeds, and `bench.iter(...)` invokes the closure again for another iteration; `client.open_uni().await` slips in before the close is processed, but eventually it makes its way through while `write_all` is still running, leading to the `Error writing` message.

Application layer race conditions on close seem to be a common landmine. We already have explicit warnings about this on the documentation for `Connection::close`, but maybe there's more we can do?

**Comment by Matthias247** [comment]
I thought about something like that. But I don't think this is the issue here:
- The repro errors on `stream.write_all(DATA).await` - not on `stream.finish()`. Since the reader only gets dropped after end of stream, and the writer did not stop in between - this should never happen.
- Whether `bench.iter` creates a new iteration shouldn't matter. The next iteration acts on a completely new stream

Besides that: Why would it not ever error with unordered reads?

I haven't checked enough yet what the semantics of Quinns `stream.finish()` operation are. I guess it waits until all data is transferred towards the peer **and** being acknowledged?  This could indeed have happened after the client consumed the data if acks are delayed. But this case still shouldn't lead the receiver to transmit a an `ApplicationClose` (likely as part of a `STOP_SENDING` frame) -> The receiver in this case already knows all data is available and the stream had been driven to completion, so rejecting at this time is pointless.

**Comment by Ralith** [comment]
> The repro errors on stream.write_all(DATA).await - not on stream.finish(). Since the reader only gets dropped after end of stream, and the writer did not stop in between - this should never happen.

I outlined two outcomes, both of which may occur depending on how the race works out. The panic on finish is one case. The other case, an error on `write_all`, occurs after a previous iteration's `finish()` succeeds and the closure is invoked again from the start.

> Whether bench.iter creates a new iteration shouldn't matter. The next iteration acts on a completely new stream

A new stream on a connection that has been closed, specifically. Writing to such a stream produces an error. The connection is closed after the first stream completes due to the `return` you added in the `Ok(None)` case, which terminates the server task and leads to all of the connection's handles being dropped.

> Besides that: Why would it not ever error with unordered reads?

The original code did not just differ in the type of read. In addition, it does not terminate the server task, but rather waits for a new stream, leaving it up to the client to close the connection when it's done.

> I haven't checked enough yet what the semantics of Quinns stream.finish() operation are. I guess it waits until all data is transferred towards the peer and being acknowledged?

`finish` completes when the peer has acknowledged all stream data at the transport layer.

> But this case still shouldn't lead the receiver to transmit a an ApplicationClose (likely as part of a STOP_SENDING frame)

`STOP_SENDING` isn't involved here, or in connection closing in general. Quinn only generates `STOP_SENDING` frames when you drop an incomplete stream or invoke `RecvStream::stop` explicitly. The receiver is closing the connection because your changes cause the task to be terminated when a stream completes, dropping all of the connection's handles.

**Comment by Matthias247** [comment]
> The connection is closed after the first stream completes due to the return you added in the Ok(None) case,

Now i got it 🤦🏻‍♂️
I didn't see the issue up to now, since I assumed the stream is handled  in a separate task. Moving it into one fixes the problem. So I guess we can close this.

> finish notifiers the peer that no more data will be sent on a stream, and completes when the peer has acknowledged all stream data at the transport layer.

Thanks for the clarification. This is kind of what I expected. Btw there might be some applications which might not want to wait for all acks from the peer, since their current equivalent on the TCP also wouldn't wait (the application closes the socket and it's up to the kernel to keep the socket alive until either everything was transmitted or the wait time elapsed).

**Comment by Ralith** [comment]
> Btw there might be some applications which might not want to wait for all acks from the peer

That's the behavior when you just drop a send stream without any ceremony: it'll be implicitly marked as complete and driven as long as necessary so long as the connection still exists, in the spirit of approximating TCP behavior. Explicitly closing the connection or shutting down the whole runtime/process will still terminate it, though.
